//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCLite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLTChassisInvoice
    {
        public string ID_CHASSIS { get; set; }
        public string INVOICE_COUNT { get; set; }
        public string INVOICE_NO { get; set; }
        public string INVOICE_COUNT_LOSE { get; set; }
        public Nullable<int> YEAR_LOSE { get; set; }
        public string INSTALL_DATE { get; set; }
        public string DEALER_CONTACT_NAME { get; set; }
        public string DEALER_CONTACT_PHONE { get; set; }
        public string ID_LICENSE { get; set; }
        public string ID_MEI { get; set; }
        public string INVOICE_NO_DATE { get; set; }
        public string INSTALL_YEAR { get; set; }
        public string INVOICE_PRICE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_PHONE { get; set; }
        public string INVOICE_CUSTOMER { get; set; }
        public string INVOICE_CUSTOMER_PHONE { get; set; }
        public int ID { get; set; }
        public string CER_LICENSE { get; set; }
        public Nullable<int> MEI_NOT_FOUND { get; set; }
        public string CER_MEI { get; set; }
        public string STATUS_CHASSIS { get; set; }
        public string STATUS_MEI { get; set; }
        public string STATUS_LICENSE { get; set; }
        public Nullable<int> STATUS_DLT { get; set; }
    }
}
