//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCLite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLTDetailChassi
    {
        public string STATUS_FLAG { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> ID_USERS { get; set; }
        public string TITLE_DETAIL { get; set; }
        public int ID { get; set; }
        public string INVOICE_FLAG { get; set; }
        public string ID_CHASSIS { get; set; }
        public string UP_DATE_INVOICE_FLAG { get; set; }
        public Nullable<System.DateTime> UP_DATE { get; set; }
        public string UP_DATE_PRICE_FLAG { get; set; }
        public string MEI { get; set; }
        public string LICENSE { get; set; }
        public string INVOICE_CUSTOMER { get; set; }
        public string DEALER_CONTACT_NAME { get; set; }
        public string CUSTOMER_NAME { get; set; }
    }
}
