//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCLite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_REPORT_CUSTOMER
    {
        public int ID { get; set; }
        public string CUSTOMER { get; set; }
        public string CONUT { get; set; }
    }
}
